http:
  listener:
    host: "localhost"
    port: "8081"
    path: "/travel-on-tip/{serviceType}"
db:
  routes:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "Root@123$"
    database: "dummy"